package tools

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/soluble-ai/go-jnode"
	"github.com/soluble-ai/soluble-cli/pkg/assessments"
	"github.com/soluble-ai/soluble-cli/pkg/blurb"
	"github.com/soluble-ai/soluble-cli/pkg/download"
	"github.com/soluble-ai/soluble-cli/pkg/log"
	"github.com/soluble-ai/soluble-cli/pkg/options"
	"github.com/soluble-ai/soluble-cli/pkg/print"
	"github.com/soluble-ai/soluble-cli/pkg/version"
	"github.com/spf13/cobra"
)

type ToolOpts struct {
	options.PrintClientOpts
	UploadEnabled         bool
	UpdatePR              bool
	ToolVersion           string
	ToolPath              string
	FailThresholds        map[string]string
	PrintAsessment        bool
	PrintResultOpt        bool
	Internal              bool
	SkipDockerPull        bool
	DisableCustomPolicies bool
	Tool                  Interface
	ParsedFailThresholds  map[string]int

	customPoliciesDir *string
}

var _ options.Interface = &ToolOpts{}

func (o *ToolOpts) GetToolOptions() *ToolOpts {
	return o
}

func (o *ToolOpts) GetDirectoryBasedToolOptions() *DirectoryBasedToolOpts {
	return nil
}

func (o *ToolOpts) Register(c *cobra.Command) {
	// set this now so help shows up, it will be corrected before we print anything
	o.Path = []string{}
	o.AuthNotRequired = true
	o.PrintClientOpts.Register(c)
	flags := c.Flags()
	flags.BoolVar(&o.UploadEnabled, "upload", false, "Upload report to Soluble")
	flags.BoolVar(&o.UpdatePR, "update-pr", false, "Update this build's pull-request with the resulting assessment")
	flags.BoolVar(&o.PrintAsessment, "print-assessment", false, "Print the full assessment response on stderr after an upload")
	flags.BoolVar(&o.PrintResultOpt, "print-result", false, "Print the JSON result from the tool on stderr")
	flags.StringToStringVar(&o.FailThresholds, "fail", nil,
		"Exit with error code 2 if the assessment generated by --upload has count or more failed findings of the given severity.  The flag should be in the form `severity=count`.  The severity levels in increasing order are: info, low, medium, high, critical.  The flag may be repeated.")
	flags.BoolVar(&o.SkipDockerPull, "skip-docker-pull", false, "Don't pull docker images before running them")
	flags.BoolVar(&o.DisableCustomPolicies, "disable-custom-policies", false, "Don't use custom policies")
	if !o.Internal {
		flags.StringVar(&o.ToolPath, "tool-path", "", "Run `tool` directly instead of using a CLI-managed version")
		flags.StringVar(&o.ToolVersion, "tool-version", "", "Override version of the tool to run (the image or github release name.)")
	}
}

func (o *ToolOpts) SetContextValues(m map[string]string) {}

func (o *ToolOpts) Validate() error {
	if o.UploadEnabled && o.GetAPIClientConfig().APIToken == "" {
		blurb.SignupBlurb(o, "{info:--upload} requires signing up with {primary:Soluble}.", "")
		return fmt.Errorf("not authenticated with Soluble")
	}
	if len(o.FailThresholds) > 0 && !o.UploadEnabled {
		return fmt.Errorf("--fail must be used with --upload")
	}
	if o.UpdatePR && !o.UploadEnabled {
		return fmt.Errorf("--update-pr must be used with --upload")
	}
	// parse here to return error upfront
	var err error
	o.ParsedFailThresholds, err = assessments.ParseFailThresholds(o.FailThresholds)
	return err
}

func (o *ToolOpts) InstallAPIServerArtifact(name, urlPath string) (*download.Download, error) {
	apiClient := o.GetAPIClient()
	m := download.NewManager()
	return m.Install(&download.Spec{
		Name:                       name,
		APIServerArtifact:          urlPath,
		APIServer:                  apiClient,
		LatestReleaseCacheDuration: 1 * time.Minute,
	})
}

func (o *ToolOpts) RunDocker(d *DockerTool) ([]byte, error) {
	if o.ToolPath != "" {
		// don't use docker, just run it directly
		// #nosec G204
		c := exec.Command(o.ToolPath, d.Args...)
		c.Dir = d.Directory
		c.Stderr = os.Stderr
		log.Infof("Running {primary:%s} {secondary:(in %s)}", strings.Join(c.Args, " "), c.Dir)
		return c.Output()
	}
	n := o.getToolVersion(d.Name)
	if image := n.Path("image"); !image.IsMissing() {
		d.Image = image.AsText()
	}
	return d.run(o.SkipDockerPull)
}

func (o *ToolOpts) InstallTool(spec *download.Spec) (*download.Download, error) {
	if o.ToolPath != "" {
		return &download.Download{
			OverrideExe: o.ToolPath,
		}, nil
	}
	if strings.HasPrefix(spec.URL, "github.com/") {
		slash := strings.LastIndex(spec.URL, "/")
		n := o.getToolVersion(spec.URL[slash+1:])
		if v := n.Path("version"); !v.IsMissing() {
			spec.RequestedVersion = v.AsText()
		}
	}
	m := download.NewManager()
	return m.Install(spec)
}

func (o *ToolOpts) getToolVersion(name string) *jnode.Node {
	if o.ToolVersion != "" {
		return jnode.NewObjectNode().
			Put("image", o.ToolVersion).
			Put("version", o.ToolVersion)
	}
	temp := log.SetTempLevel(log.Error - 1)
	defer temp.Restore()
	n, err := o.GetUnauthenticatedAPIClient().Get(fmt.Sprintf("cli/tools/%s/config", name))
	if err != nil {
		return jnode.MissingNode
	}
	return n
}

func (o *ToolOpts) PrintToolResult(result *Result) {
	o.Columns = result.PrintColumns
	if result.Findings != nil {
		o.Path = []string{}
		o.WideColumns = append(o.WideColumns, "repoPath", "partialFingerprint")
		o.SetFormatter("pass", func(n *jnode.Node) string {
			if n.AsBool() {
				return "PASS"
			}
			return "FAIL"
		})
		d, _ := json.Marshal(result.Findings)
		n, _ := jnode.FromJSON(d)
		o.PrintResult(n)
		return
	}
	o.Path = result.PrintPath
	o.Columns = result.PrintColumns
	o.PrintResult(result.Data)
}

func (o *ToolOpts) RunTool(printResult bool) (*Result, error) {
	result, err := o.Tool.Run()
	if err != nil || result == nil {
		return nil, err
	}
	result.AddValue("TOOL_NAME", o.Tool.Name()).
		AddValue("CLI_VERSION", version.Version)
	if diropts := o.Tool.GetDirectoryBasedToolOptions(); diropts != nil {
		result.Findings.ComputePartialFingerprints(diropts.GetDirectory())
	}
	if printResult {
		o.PrintToolResult(result)
	}
	if o.PrintResultOpt {
		p := &print.JSONPrinter{}
		p.PrintResult(os.Stderr, result.Data)
	}
	if o.UploadEnabled {
		err = result.Report(o.Tool)
		if err == nil && o.UpdatePR {
			if result.Assessment != nil {
				err = result.Assessment.UpdatePR(o.GetAPIClient())
			}
		}
	}
	return result, err
}

func (o *ToolOpts) GetCustomPoliciesDir() (string, error) {
	if o.customPoliciesDir != nil {
		return *o.customPoliciesDir, nil
	}
	if o.GetAPIClientConfig().APIToken == "" {
		return "", nil
	}
	d, err := o.InstallAPIServerArtifact(fmt.Sprintf("%s-policies", o.Tool.Name()),
		fmt.Sprintf("/api/v1/org/{org}/rules/%s/rules.tgz", o.Tool.Name()))
	if err != nil {
		return "", err
	}
	// if the directory is empty, then treat that the same as no custom policies
	fs, err := ioutil.ReadDir(d.Dir)
	if err != nil {
		return "", err
	}
	if len(fs) == 0 {
		var zero string
		o.customPoliciesDir = &zero
		log.Infof("{primary:%s} has no custom policies", o.Tool.Name())
	} else {
		o.customPoliciesDir = &d.Dir
		fmt.Println(d.Dir)
	}
	return *o.customPoliciesDir, nil
}
