version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - "> 1.37.3, < 1.38"
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.36.33
    - 1.37.1
