name: CI

on:
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Fetching tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Setting up go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: Caching go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Installing golangci-lint
      run: wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.23.8
    - name: Test and build binaries
      run: ./hack/build.sh
    - name: Distribute Release
      run: ./hack/dist.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

